from __future__ import annotations

from pathlib import Path

import pickle
import pandas as pd
import streamlit as st

from src.ml_assignment.metrics import confusion_frame, evaluate_predictions


ROOT = Path(__file__).resolve().parent
ARTIFACT_DIR = ROOT / "artifacts"
MODEL_DIR = ARTIFACT_DIR / "model"


st.set_page_config(page_title="ML Assignment 2", page_icon="📊", layout="wide")


@st.cache_resource
def load_artifacts():
    artifacts = {}
    for model_path in sorted(MODEL_DIR.glob("*.pkl")):
        with open(model_path, "rb") as f:
            payload = pickle.load(f)
        artifacts[payload["name"]] = payload
    metrics_path = ARTIFACT_DIR / "metrics.csv"
    metrics = pd.read_csv(metrics_path) if metrics_path.exists() else pd.DataFrame()
    test_data_path = ARTIFACT_DIR / "test_data.csv"
    test_data = pd.read_csv(test_data_path) if test_data_path.exists() else pd.DataFrame()
    return {"models": artifacts, "metrics": metrics, "test_data": test_data}


def predict_with_artifact(artifact, frame: pd.DataFrame):
    feature_names = artifact["feature_names"]
    X = frame[feature_names]
    X_processed = artifact["preprocess"].transform(X)
    model = artifact["model"]
    y_pred = model.predict(X_processed)
    if hasattr(model, "predict_proba"):
        y_prob = model.predict_proba(X_processed)[:, 1]
    else:
        scores = model.decision_function(X_processed)
        y_prob = (scores - scores.min()) / (scores.max() - scores.min() + 1e-12)
    return y_pred, y_prob


def main():
    st.title("Machine Learning Assignment 2")
    st.caption("UCI Breast Cancer Wisconsin classification comparison across six models.")

    artifacts = load_artifacts()
    model_names = list(artifacts["models"].keys())

    if not model_names:
        st.error("No saved models were found. Run `python train_models.py` first.")
        st.stop()

    with st.sidebar:
        st.header("Controls")
        selected_model = st.selectbox("Choose a model", model_names)
        uploaded_file = st.file_uploader("Upload test data CSV", type=["csv"])
        st.info("Upload only the test data CSV generated by `train_models.py` or a compatible CSV with the same feature columns.")

    base_df = artifacts["test_data"]
    if base_df.empty:
        st.error("The saved test data file is missing. Run `python train_models.py` first.")
        st.stop()

    if uploaded_file is not None:
        data = pd.read_csv(uploaded_file)
        st.success("Using uploaded CSV for predictions.")
    else:
        data = base_df.copy()
        st.info("Using the saved `test_data.csv` by default. Upload another CSV to replace it.")

    artifact = artifacts["models"][selected_model]
    feature_names = artifact["feature_names"]

    missing = [col for col in feature_names if col not in data.columns]
    if missing:
        st.error(f"Uploaded file is missing required columns: {missing}")
        st.stop()

    if "target" in data.columns:
        y_true = data["target"]
    else:
        y_true = base_df["target"].iloc[: len(data)].reset_index(drop=True)
        data = data.copy()
        data["target"] = y_true.values

    y_pred, y_prob = predict_with_artifact(artifact, data)
    eval_metrics = evaluate_predictions(y_true, y_pred, y_prob)

    col1, col2, col3, col4, col5, col6 = st.columns(6)
    col1.metric("Accuracy", f"{eval_metrics['accuracy']:.4f}")
    col2.metric("AUC", f"{eval_metrics['auc']:.4f}")
    col3.metric("Precision", f"{eval_metrics['precision']:.4f}")
    col4.metric("Recall", f"{eval_metrics['recall']:.4f}")
    col5.metric("F1", f"{eval_metrics['f1']:.4f}")
    col6.metric("MCC", f"{eval_metrics['mcc']:.4f}")

    st.subheader("Confusion Matrix")
    st.dataframe(confusion_frame(y_true, y_pred), use_container_width=True)

    st.subheader("Predictions Preview")
    preview = data[feature_names].copy()
    preview["actual"] = y_true.values
    preview["prediction"] = y_pred
    preview["probability"] = y_prob
    st.dataframe(preview.head(25), use_container_width=True)

    st.subheader("Model Comparison Table")
    metrics_df = artifacts["metrics"]
    if not metrics_df.empty:
        st.dataframe(metrics_df.sort_values("accuracy", ascending=False), use_container_width=True)

    st.subheader("Loaded Data Source")
    st.write("Current source:", "Uploaded CSV" if uploaded_file is not None else "Saved test_data.csv")
    st.dataframe(data.head(25), use_container_width=True)


if __name__ == "__main__":
    main()
